### PR TITLE
[ENH] Update icons and DMG installer

### PR DESCRIPTION
**Pull request by markotoplak**
From material from biolab/orange-graphics@6e4cdf5093bc5d66d595550aeaaa42ea9a2be0c6

I replaced our custom dmg-creation script with create-dmg, which allows easier editing of DMG installations screens.

I also removed conda-build's meta.yaml from this repo - now it uses the one from orange3.

### CODE REVIEW

**Comment by markotoplak** [comment]
DMG install screen is not ideal because the background is too small, therefore the icons come too close to the borders. But that could be fixed in a separate PR (the DMGs are now much easier to edit).

**Comment by markotoplak** [comment]
@ales-erjavec, could you perhaps consider reviewing/merging this? Thanks.

**Comment by ales-erjavec** [comment]
This PR still has [NOMERGE] commits.

**Comment by markotoplak** [comment]
I removed [NOMERGE] commits, thanks.

**Pull request merged**
